/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec;

/**
 *
 * @author guerr
 */
public class tela_cadastroVisitante extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_cadastroVisitante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        lbl_rg = new javax.swing.JLabel();
        lbl_tipoVisitante = new javax.swing.JLabel();
        lbl_codVisitante = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        txt_rg = new javax.swing.JTextField();
        txt_codVisitante = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        lbl_telefone1 = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        txt_cep = new javax.swing.JTextField();
        lbl_cep = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JToggleButton();
        btn_limpar = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_nome.setText("Nome:");
        getContentPane().add(lbl_nome);
        lbl_nome.setBounds(18, 31, 31, 14);

        lbl_telefone.setText("Telefone:");
        getContentPane().add(lbl_telefone);
        lbl_telefone.setBounds(205, 80, 46, 14);

        lbl_rg.setText("RG:");
        getContentPane().add(lbl_rg);
        lbl_rg.setBounds(18, 110, 18, 14);

        lbl_tipoVisitante.setText("Tipo de Visitante:");
        getContentPane().add(lbl_tipoVisitante);
        lbl_tipoVisitante.setBounds(205, 113, 83, 14);

        lbl_codVisitante.setText("Código de Visitante:");
        getContentPane().add(lbl_codVisitante);
        lbl_codVisitante.setBounds(96, 142, 96, 14);
        getContentPane().add(txt_nome);
        txt_nome.setBounds(77, 25, 323, 20);

        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txt_telefone);
        txt_telefone.setBounds(298, 77, 102, 20);
        getContentPane().add(txt_rg);
        txt_rg.setBounds(77, 107, 90, 20);

        txt_codVisitante.setText("jTextField1");
        txt_codVisitante.setOpaque(false);
        getContentPane().add(txt_codVisitante);
        txt_codVisitante.setBounds(202, 138, 85, 23);

        jToggleButton1.setText("Gerar Código");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(297, 138, 103, 23);

        lbl_telefone1.setText("Endereço:");
        getContentPane().add(lbl_telefone1);
        lbl_telefone1.setBounds(18, 54, 49, 14);
        getContentPane().add(txt_endereco);
        txt_endereco.setBounds(77, 51, 323, 20);

        txt_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cepActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cep);
        txt_cep.setBounds(77, 77, 90, 20);

        lbl_cep.setText("CEP:");
        getContentPane().add(lbl_cep);
        lbl_cep.setBounds(18, 80, 23, 14);

        btn_cadastrar.setText("Cadastrar");
        getContentPane().add(btn_cadastrar);
        btn_cadastrar.setBounds(118, 167, 138, 35);

        btn_limpar.setText("Limpar Dados");
        getContentPane().add(btn_limpar);
        btn_limpar.setBounds(262, 167, 138, 35);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(298, 107, 102, 20);

        jButton1.setText("Alterar");
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 210, 130, 40);

        jButton2.setText("Excluir");
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 210, 140, 40);

        setSize(new java.awt.Dimension(705, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cepActionPerformed

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastroVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_cadastrar;
    private javax.swing.JToggleButton btn_limpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_cep;
    private javax.swing.JLabel lbl_codVisitante;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JLabel lbl_telefone1;
    private javax.swing.JLabel lbl_tipoVisitante;
    private javax.swing.JTextField txt_cep;
    private javax.swing.JTextField txt_codVisitante;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
