/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec;

import java.awt.ComponentOrientation;
import javax.swing.JFrame;

/**
 *
 * @author guerr
 */
public class tela_menu extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        img_backgroundmenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbl_consultar = new javax.swing.JMenu();
        consultar_visitantes = new javax.swing.JMenuItem();
        consultar_eventos = new javax.swing.JMenuItem();
        consultar_obras = new javax.swing.JMenuItem();
        lbl_cadastro = new javax.swing.JMenu();
        cadastrar_visitante = new javax.swing.JMenuItem();
        cadastrar_obra = new javax.swing.JMenuItem();
        cadastrar_evento = new javax.swing.JMenuItem();
        lbl_loja = new javax.swing.JMenu();
        loja_gerenciarE = new javax.swing.JMenuItem();
        loja_novoProduto = new javax.swing.JMenuItem();
        loja_relatorios = new javax.swing.JMenuItem();
        lbl_restauracao = new javax.swing.JMenu();
        lbl_novoChamado = new javax.swing.JMenuItem();
        lbl_verificarChamado = new javax.swing.JMenuItem();
        lbl_sair = new javax.swing.JMenu();
        lbl_logoff = new javax.swing.JMenuItem();
        lbl_close = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        img_backgroundmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Sem Título-1.png"))); // NOI18N
        getContentPane().add(img_backgroundmenu);
        img_backgroundmenu.setBounds(0, 0, 680, 430);

        jMenuBar1.setBackground(new java.awt.Color(255, 167, 94));

        lbl_consultar.setText("Consultar");

        consultar_visitantes.setText("Visitantes");
        consultar_visitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultar_visitantesMouseClicked(evt);
            }
        });
        consultar_visitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_visitantesActionPerformed(evt);
            }
        });
        lbl_consultar.add(consultar_visitantes);

        consultar_eventos.setText("Eventos");
        consultar_eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_eventosActionPerformed(evt);
            }
        });
        lbl_consultar.add(consultar_eventos);

        consultar_obras.setText("Obras");
        consultar_obras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_obrasActionPerformed(evt);
            }
        });
        lbl_consultar.add(consultar_obras);

        jMenuBar1.add(lbl_consultar);

        lbl_cadastro.setText("Cadastrar");
        lbl_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cadastroMouseClicked(evt);
            }
        });
        lbl_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_cadastroActionPerformed(evt);
            }
        });

        cadastrar_visitante.setText("Visitantes");
        cadastrar_visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_visitanteActionPerformed(evt);
            }
        });
        lbl_cadastro.add(cadastrar_visitante);

        cadastrar_obra.setText("Obras");
        cadastrar_obra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_obraActionPerformed(evt);
            }
        });
        lbl_cadastro.add(cadastrar_obra);

        cadastrar_evento.setText("Eventos");
        cadastrar_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_eventoActionPerformed(evt);
            }
        });
        lbl_cadastro.add(cadastrar_evento);

        jMenuBar1.add(lbl_cadastro);

        lbl_loja.setText("Loja");

        loja_gerenciarE.setText("Estoque");
        loja_gerenciarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loja_gerenciarEActionPerformed(evt);
            }
        });
        lbl_loja.add(loja_gerenciarE);

        loja_novoProduto.setText("Novo produto");
        lbl_loja.add(loja_novoProduto);

        loja_relatorios.setText("Relatórios");
        lbl_loja.add(loja_relatorios);

        jMenuBar1.add(lbl_loja);

        lbl_restauracao.setText("Restauração ");

        lbl_novoChamado.setText("Novo Chamado");
        lbl_restauracao.add(lbl_novoChamado);

        lbl_verificarChamado.setText("Verificar Chamados");
        lbl_verificarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_verificarChamadoActionPerformed(evt);
            }
        });
        lbl_restauracao.add(lbl_verificarChamado);

        jMenuBar1.add(lbl_restauracao);

        lbl_sair.setText("Sair");
        lbl_sair.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                lbl_sairCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        lbl_logoff.setText("Fazer logoff");
        lbl_logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_logoffActionPerformed(evt);
            }
        });
        lbl_sair.add(lbl_logoff);

        lbl_close.setText("Fechar Programa");
        lbl_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_closeActionPerformed(evt);
            }
        });
        lbl_sair.add(lbl_close);

        jMenuBar1.add(lbl_sair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(681, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loja_gerenciarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loja_gerenciarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loja_gerenciarEActionPerformed

    private void consultar_visitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_visitantesActionPerformed
        new tela_consultarVisitante().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_visitantesActionPerformed

    private void lbl_verificarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_verificarChamadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_verificarChamadoActionPerformed

    private void cadastrar_obraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_obraActionPerformed
        // TODO add your handling code here:
        new tela_cadastroObra().setVisible(true);
    }//GEN-LAST:event_cadastrar_obraActionPerformed

    private void cadastrar_visitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_visitanteActionPerformed
        // TODO add your handling code here:
        new tela_cadastroVisitante().setVisible(true);
    }//GEN-LAST:event_cadastrar_visitanteActionPerformed

    private void lbl_cadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cadastroMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_lbl_cadastroMouseClicked

    private void consultar_visitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultar_visitantesMouseClicked
    }//GEN-LAST:event_consultar_visitantesMouseClicked

    private void lbl_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_cadastroActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_cadastroActionPerformed

    private void consultar_eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_eventosActionPerformed
        // TODO add your handling code here:
        new tela_consultarEvento().setVisible(true);
    }//GEN-LAST:event_consultar_eventosActionPerformed

    private void consultar_obrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_obrasActionPerformed
        // TODO add your handling code here:
        new tela_consultarObra().setVisible(true);
    }//GEN-LAST:event_consultar_obrasActionPerformed

    private void cadastrar_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_eventoActionPerformed
        // TODO add your handling code here:
        new tela_cadastroEvento().setVisible(true);
    }//GEN-LAST:event_cadastrar_eventoActionPerformed

    private void lbl_logoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_logoffActionPerformed
        // TODO add your handling code here:
            new tela_login().setVisible(true);
            new tela_menu().setVisible(false);
    }//GEN-LAST:event_lbl_logoffActionPerformed

    private void lbl_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_closeActionPerformed
        System.exit(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_lbl_closeActionPerformed

    private void lbl_sairCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbl_sairCaretPositionChanged

    lbl_sair.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_sairCaretPositionChanged


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrar_evento;
    private javax.swing.JMenuItem cadastrar_obra;
    private javax.swing.JMenuItem cadastrar_visitante;
    private javax.swing.JMenuItem consultar_eventos;
    private javax.swing.JMenuItem consultar_obras;
    private javax.swing.JMenuItem consultar_visitantes;
    private javax.swing.JLabel img_backgroundmenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu lbl_cadastro;
    private javax.swing.JMenuItem lbl_close;
    private javax.swing.JMenu lbl_consultar;
    private javax.swing.JMenuItem lbl_logoff;
    private javax.swing.JMenu lbl_loja;
    private javax.swing.JMenuItem lbl_novoChamado;
    private javax.swing.JMenu lbl_restauracao;
    private javax.swing.JMenu lbl_sair;
    private javax.swing.JMenuItem lbl_verificarChamado;
    private javax.swing.JMenuItem loja_gerenciarE;
    private javax.swing.JMenuItem loja_novoProduto;
    private javax.swing.JMenuItem loja_relatorios;
    // End of variables declaration//GEN-END:variables
}
