/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec;

/**
 *
 * @author guerr
 */
public class tela_cadastroObra extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_cadastroObra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tituloObra = new javax.swing.JTextField();
        txt_autorObra = new javax.swing.JTextField();
        txt_dataObra = new javax.swing.JTextField();
        txt_estadoObra = new javax.swing.JTextField();
        cmb_tipo = new javax.swing.JComboBox<String>();
        btn_data = new javax.swing.JToggleButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Titulo da obra:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 28, 99, 18);

        jLabel2.setText("Autor da obra:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 54, 98, 18);

        jLabel3.setText("Data da obra:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 92, 18);

        jLabel5.setText("Estado da obra:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 109, 107, 18);

        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(63, 135, 34, 18);
        getContentPane().add(txt_tituloObra);
        txt_tituloObra.setBounds(91, 25, 210, 30);
        getContentPane().add(txt_autorObra);
        txt_autorObra.setBounds(91, 51, 210, 30);
        getContentPane().add(txt_dataObra);
        txt_dataObra.setBounds(91, 77, 90, 30);
        getContentPane().add(txt_estadoObra);
        txt_estadoObra.setBounds(91, 106, 210, 30);

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmb_tipo);
        cmb_tipo.setBounds(91, 132, 210, 30);

        btn_data.setText("jToggleButton1");
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data);
        btn_data.setBounds(187, 77, 24, 20);

        btn_cadastrar.setText("Cadastrar");
        getContentPane().add(btn_cadastrar);
        btn_cadastrar.setBounds(91, 163, 98, 39);

        btn_limpar.setText("Limpar dados");
        getContentPane().add(btn_limpar);
        btn_limpar.setBounds(195, 163, 106, 39);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/background_geral.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-270, -90, 790, 520);

        setSize(new java.awt.Dimension(347, 252));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastroObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JToggleButton btn_data;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txt_autorObra;
    private javax.swing.JTextField txt_dataObra;
    private javax.swing.JTextField txt_estadoObra;
    private javax.swing.JTextField txt_tituloObra;
    // End of variables declaration//GEN-END:variables
}
