package br.com.fatec;

import com.mysql.jdbc.MySQLConnection;
import com.mysql.jdbc.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/**
 *
 * @author guerr
 */
public class tela_login extends javax.swing.JFrame {
   
    /**
     * Creates new form tela_login
     */
    public tela_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_usuario = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        txt_senha = new javax.swing.JPasswordField();
        txt_login = new javax.swing.JTextField();
        lbl_esqueceusenha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_usuario.setText("Usuário:");
        getContentPane().add(lbl_usuario);
        lbl_usuario.setBounds(50, 120, 60, 18);

        lbl_senha.setText("Senha:");
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(50, 150, 50, 18);

        btn_login.setBackground(new java.awt.Color(255, 255, 204));
        btn_login.setText("Entrar");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(300, 110, 120, 60);

        txt_senha.setText("jPasswordField1");
        txt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_senha);
        txt_senha.setBounds(110, 140, 190, 30);

        txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(txt_login);
        txt_login.setBounds(110, 110, 190, 30);

        lbl_esqueceusenha.setForeground(new java.awt.Color(0, 0, 255));
        lbl_esqueceusenha.setText("Esqueceu sua senha?");
        lbl_esqueceusenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_esqueceusenhaMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_esqueceusenha);
        lbl_esqueceusenha.setBounds(170, 170, 140, 18);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/background_login.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 200);

        setSize(new java.awt.Dimension(454, 222));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginActionPerformed
        // TODO add your handling code here:
       String sql = "Select * from tb_usuario where usuario=? and senha=?";
       connectionFactory con = (connectionFactory) new connectionFactory().getConnection();
       PreparedStatement ps;
       Connection connection = null;
    try{
           connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_museu", "root", "");

           ps = connection.prepareStatement("SELECT 'usuario','senha'FROM 'tb_usuario' WHERE 'usuario'=? AND 'senha'=?");
           ps.setString(1,txt_login.getText());
           ps.setString(2, String.valueOf(txt_senha.getPassword()));
           ResultSet result = ps.executeQuery();
           if(result.next()){
               JOptionPane.showConfirmDialog(rootPane, "Login com sucesso!");
                       new tela_menu().setVisible(true);
           }
           else
           {
                              JOptionPane.showConfirmDialog(rootPane, "usuario ou senha invalido!");

           }
    }   catch (SQLException ex) {
            Logger.getLogger(tela_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_loginActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
      
            
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaActionPerformed

    private void lbl_esqueceusenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_esqueceusenhaMouseClicked
        // TODO add your handling code here:
        
               new tela_recup().setVisible(true);
    }//GEN-LAST:event_lbl_esqueceusenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_esqueceusenha;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
